CREATE DATABASE IF NOT EXISTS ticketdb;
USE ticketdb;

CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY, 
	username VARCHAR(50) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	session_key VARCHAR(128) NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	expires_at DATETIME NOT NULL,
	is_active TINYINT(1) DEFAULT 1,
	FOREIGN KEY (user_id) REFERENCES users(id)
);

